### ISSUE TITLE
Mouse hover text

### ISSUE THREAD

**Issue by thunder87** [sixlive/nova-text-copy-field#16]
## What are the steps to reproduce this issue?

Hover the icon

## What were you expecting to happen?
Hover text with localization to tell the user what clicking it does.

**Comment by sixlive** [comment]
This sounds good. I'll try and get it done by the end of the weekend.

**Comment by sixlive** [comment]
@thunder87 can you take a look at #18 and let me know if this satisfies your needs?

**Comment by thunder87** [comment]
Should work perfectly! Thanks 👍

**Comment by sixlive** [comment]
I ended up going down a rabbit hole trying to get this thing tested. I'll work on getting these couple open features merged and tagged over the next couple of days.

**Comment by thunder87** [comment]
It's one deep rabbit hole, eta on this being merged :)

**Comment by sixlive** [comment]
I'm working on getting it merged and tagged right now.

**Comment by sixlive** [comment]
https://github.com/sixlive/nova-text-copy-field/releases/tag/v1.3.0

**Comment by thunder87** [comment]
Thanks 🥇 working perfectly!
