### ISSUE TITLE
Different data in clipboard

### ISSUE THREAD

**Issue by thunder87** [sixlive/nova-text-copy-field#17]
## Different data in clipboard

Let's say i have this url: https://my-long-url-example.com/1S79Z

but i only want to show **1S79Z** in the table.

**Comment by sixlive** [comment]
I'll look into this over the next couple days

**Comment by sixlive** [comment]
@thunder87 take a look at #19 and see if this is what you were looking for.

**Comment by thunder87** [comment]
Should work perfectly! Thanks 👍

**Comment by sixlive** [comment]
I ended up going down a rabbit hole trying to get this thing tested. I'll work on getting these couple open features merged and tagged over the next couple of days.

**Comment by thunder87** [comment]
It's one deep rabbit hole, eta on this being merged :)

**Comment by sixlive** [comment]
I'm working on getting it merged and tagged right now.

**Comment by sixlive** [comment]
Merged with https://github.com/sixlive/nova-text-copy-field/pull/19

**Comment by sixlive** [comment]
https://github.com/sixlive/nova-text-copy-field/releases/tag/v1.3.0

**Comment by thunder87** [comment]
Thanks! 🥇
