### ISSUE TITLE
Show icon only on text hover

### ISSUE THREAD

**Issue by ben182** [sixlive/nova-text-copy-field#23]
##  Description
What about hiding the icon until someone hovers over the text? Like Digitalocean does.

**Comment by sixlive** [comment]
Can you create a gif example?

**Comment by ben182** [comment]
![image](https://user-images.githubusercontent.com/17678582/51624970-579e4600-1f3c-11e9-96c7-3d90d4a4bef9.png)

**Comment by ben182** [comment]
![ezgif-5-94a4d2f5cbc4](https://user-images.githubusercontent.com/17678582/51625006-7270ba80-1f3c-11e9-90d6-f18160851391.gif)

**Comment by ben182** [comment]
That would improve UX because if you have many records the view gets a bit messy
![image](https://user-images.githubusercontent.com/17678582/51625166-c7143580-1f3c-11e9-9c52-ecf2f02e6e3b.png)

**Comment by sixlive** [comment]
I dig it! It will have to wait until the weekend, but I'm down to implement it.

**Comment by ben182** [comment]
Perfect Thanks

**Comment by sixlive** [comment]
@ben182 take a look at https://github.com/sixlive/nova-text-copy-field/pull/25 and see what you think.

**Comment by ben182** [comment]
@sixlive perfect thank you!

**Comment by sixlive** [comment]
I’m wondering if there is something we can do to “hint” that there is an additional hidden action. Got any ideas? Just add an underline?

**Comment by ben182** [comment]
I don't think that's necessary. If you give a hint, you can also display the icon right from the start. Digitalocean have one of the best UI designers and don't solve it differently.

**Comment by ben182** [comment]
Underline always means that the user can click something. Links etc

**Comment by sixlive** [comment]
Yeah, it’s tough. I’ll leave it as is in the PR.
